In [5]:
import math
class logistic_regression:
    def __init__(self,learning_rate=0.01,max_iter=1000):
        self.learning_rate=learning_rate
        self.max_iter=max_iter
        self.weights=None
        self.cost_history=[]
    @staticmethod
    def _sigmoid(z):
        return 1/(1+math.exp(-z))
    def initialize_weights(self,n_features):
        self.weights=[0,0]*(n_features+1)
    def _compute_cost(self,X,y):
        total_cost=0
        m=len(X)
        for i in range(m):
            z=self.weights[0]
            for j in range(len(X[i])):
                z+=self.weights[j+1]*X[i][j]
            prediction=self._sigmoid(z)
            if y[i]==1:
                total_cost+=-math.log(prediction)
            else:
                total_cost+=-math.log(1-prediction)
    def fit(self,X,y):
        n_features=len(X[0]) if X else 0
        self._initialize_weigths(n_features)
        m=len(X)
        for iteration in range(self.max_iter):
            gradient_bias=0
            gradient_weights=[0]*n_features
            for i in range(m):
                z=self.weights[0]
                for j in range(n_features):
                    z+=self.weights[j+1]*X[i][j]
                prediction=self._sigmoid(z)
                error=prediction-y[i]
                gradient_bias+=error
                for j in range(n_features):
                    gradient_weights[j]+=error*X[i][j]
            self.weights[0]-=(self.learning_rate*gradient_bias)/m
            for j in range(n_features):
                self.weights[j+1]-=(self.learning_rate*gradient_weights[j])/m
            if iteration%100==0:
                self.cost_history.append(self._compute_cost(X,y))
    def predict_prob(self,X):
        probabilities=[]
        for features in X:
            z=self.weights[0]
            for j in range(len(features)):
                z+=self.weights[j+1]*features[j]
            probabilities.append(self._sigmoid(z))
        return probabilities
    def predict(self,X,threshold=0.5):
        return [1 if p>=threshold else 0 for p in self.predict_prob(X)]
    def get_weights(self):
        return {
            'bias':self.weights[0],
            'coefficients':self.weights[1:]
        }

In [3]:
data=[[1,0],[2,0],[3,1],[4,1],[1,1],[2,1],[2.5,0]] 
data[:5]

[[1, 0], [2, 0], [3, 1], [4, 1], [1, 1]]

In [34]:
def trace(arr:list)->int:
    flat_mat=[arr[i][j] for i in range(len(arr[0])) for j in range(len(arr))]
    return sum([flat_mat[i] for i in range(len(flat_mat)) if flat_mat[i]==1])
x=[[1,0,0,0],[0,0,1,0],[0,0,0,1],[0,1,0,0]]
trace(x)

4

In [33]:
import numpy as np 

In [103]:
arr=[[1,3,2],[5,10,3],[5,3,5]]
def det(arr:list[int|float]):
    det_list=arr[0]
    ig_col=[]
    det:int|float=0
    calc_2=lambda arr:arr[0]*arr[len(arr)-1]-arr[1]*arr[len(arr)-2]
    for i in range(len(arr)):
        temp=[0,i]
        full_arr=[[i,j] for i in range(len(arr)) for j in range(len(arr))]
        ignore_row=[[0,j] for j in range(len(arr)) if [0,j]!=temp]
        ignore_col=[[j,i] for j in range(len(arr)) ]
        
        ignore=ignore_col+ignore_row
        temp_row=[[i,j] for i in range(len(arr)) for j in range(len(arr)) if [i,j] not in ignore]
        x=[arr[i][j] for i in range(len(arr)) for j in range(len(arr)) if [i,j] not in ignore]
        det+=calc_2(x)*det_list[i] if i!=1 else -1*(det_list[i]*calc_2(x))
    return det
    
    
det(arr)

-59

In [22]:
arr=[[1,3,2],[5,10,3],[5,3,5]]
def det(arr:list[int|float]):
    det_list=arr[0]
    ig_col=[]
    det:int|float=0
    calc_2=lambda arr:arr[0]*arr[len(arr)-1]-arr[1]*arr[len(arr)-2]
    for i in range(len(arr)):
        temp=[0,i]
        full_arr=[[i,j] for i in range(len(arr)) for j in range(len(arr))]
        ignore_row=[[0,j] for j in range(len(arr)) if [0,j]!=temp]
        ignore_col=[[j,i] for j in range(len(arr)) ]
        
        ignore=ignore_col+ignore_row
        temp_row=[[i,j] for i in range(len(arr)) for j in range(len(arr)) if [i,j] not in ignore]
        x=[arr[i][j] for i in range(len(arr)) for j in range(len(arr)) if [i,j] not in ignore]
        det+=calc_2(x)*det_list[i] if i!=1 else -1*(det_list[i]*calc_2(x))
    return det
    
    
det(arr)

-59

In [45]:
''' custome implementation of matrix multiplication 
'''
def multiply(arr1,arr2)->list:
    assert len(arr1[0])==len(arr2), "ERROR:: for arr1=5X6 arr2 should be 6X5  "
    res=[[0]*len(arr1)]*len(arr1)
    temp=[]
    for i in range(len(arr1)):
        for j in range(len(arr1)):
            x=[k[j] for k in arr2]
            y=arr1[i]
            z=sum([x[n]*y[n] for n in range(len(x))])
            temp.append(z)
           
            
    temp=reshape(temp,len(arr1),len(arr1))
            
    return temp 
    
    
    
arr1=[[1,3,2],[4,2,4],[2,1,3]]
arr2=[[23,4,1],[1,34,34],[23,1,2]]
multiply(arr1,arr2)

[[72, 108, 107], [186, 88, 80], [116, 45, 42]]

In [23]:
def transpose(l):
    columns=len(l[0])
    rows=len(l)
    r=[]
    i=[]
    for column in range(columns):
        for row in range(rows):
            r.append(l[row][column])
    return reshape(r,rows=columns,columns=rows)
def reshape(matrix,rows,columns): 
    res=[[None]*columns]*rows
    k,i=0,columns
    for row in range(rows):
        res[row]=matrix[0:][k:i]
        k=i
        i+=columns
    return res
        
    
             
transpose([[2,3,5],[56,3,4],[4,5,67],[56,6,4],[66,5,7],[3,6,67]])

[[2, 56, 4, 56, 66, 3], [3, 3, 5, 6, 5, 6], [5, 4, 67, 4, 7, 67]]

In [3]:



# def eig(matrix):
#     ''' we are gonna use the QR algorithm for it '''
#     assert len(matrix)==len(matrix[0]),"fuck you bitch it is not square matrix"
#     is_1=lambda val:  1 if val in [[0,0],[1,1],[2,2]]  else 0 
    
#     I=[[is_1([i,j]) for i in range(len(matrix))] for j in range(len(matrix)) ]
#     return  [ [matrix[j][i]-I[j][i] for i in range(len(matrix))]  for j in range(len(matrix))]
def QR_decomposer(matrix):
    import math
    assert len(matrix)==len(matrix),'it should be a square matrix dumb ass '
    dot=lambda m1,m2: sum([m1[i]*m2[i] for i in range(len(m1))])
    norm=lambda m: math.sqrt(sum([m[i]**2 for i in range(len(m))]))
    a1=[matrix[i][0] for i in range(len(matrix))]
    a2=[matrix[i][1] for i  in range(len(matrix))]
    a3=[matrix[i][2] for i in range(len(matrix))]
    e1=[(a1[i]/(norm(a1))) for i in range(len(a1))]
    u2=[(a2[i]-dot(a2,e1)*e1[i]) for i in range(len(a2))]
    e2=[(u2[i]/norm(u2)) for i in range(len(u2))]
    u3=[(a3[i]-((dot(a3,e1)*e1[i])+(dot(a3,e2)*e2[i]))) for i in range(len(a3))]
    e3=[(u3[i]/norm(u3)) for i in range(len(u3))]
    temp=[e1,e2,e3]
    Q=[[temp[i][j] for i in range(len(temp))] for j in range(len(temp))] 
    row_fil=[a1,a2,a3]
    row_fill2=[e1,e2,e3]
    fill_val=lambda val: 0 if val in [[1,0],[2,0],[2,1]] else dot(row_fil[val[1]],row_fill2[val[0]]) 
    R=[[fill_val([j,i]) for i in range(3)]for j in range(3)]
    return Q,R


    

QR_decomposer([[1,1,0],[1,0,1],[0,1,1]])

([[0.7071067811865475, 0.40824829046386313, -0.5773502691896256],
  [0.7071067811865475, -0.40824829046386296, 0.5773502691896258],
  [0.0, 0.8164965809277261, 0.5773502691896255]],
 [[1.414213562373095, 0.7071067811865475, 0.7071067811865475],
  [0, 1.2247448713915894, 0.4082482904638632],
  [0, 0, 1.1547005383792515]])

In [74]:

[].append(20)


def orthogonal_valid(matrix):
    assert len(matrix)==len(matrix[0]),"valid for square matrix yu fuckin donkey"
    is_1=lambda val:  1 if val in [[0,0],[1,1],[2,2]]  else 0 
    I=[[is_1([i,j]) for i in range(len(matrix))] for j in range(len(matrix)) ]
    return multiply(matrix,transpose(matrix))==I



orthogonal_valid([[1,1,0],[1,0,1],[0,1,1]])

False

In [44]:
''' makes an upper triangular matrix '''
def upper_triangle(matrix):
    fill=lambda val:0 if val in [[1,0],[2,0],[2,1]] else matrix[val[0]][val[1]]
    return [[fill([j,i]) for i in range(3)]for j in range(3)]
matrix=[[1,2,3],[3,2,1],[3,2,1]]
upper_triangle(matrix)

[[1, 2, 3], [0, 2, 1], [0, 0, 1]]

In [5]:
''' return the max indice of a matrix '''
def argmax(arr):
    assert arr[0]!=int,"array should be 1 dimenional"
    x=[i for i in range(len(arr))]
    return max(x)
argmax([1,3,4])
    

2

In [96]:
''' how to make a diagonal matrix  '''
def diag():
    row,col=3,3
    is_valid=lambda val: 1 if val in [[0,0],[1,1],[2,2]] else 0
    return [[is_valid([j,i]) for i in range(col) ] for j in range(row)]
diag() 

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [3]:
import numpy as np
x,y =np.linalg.qr([[1,1,0],[1,0,1],[0,1,1]])
np.diag(x),x

(array([-0.70710678, -0.40824829,  0.57735027]),
 array([[-0.70710678,  0.40824829, -0.57735027],
        [-0.70710678, -0.40824829,  0.57735027],
        [-0.        ,  0.81649658,  0.57735027]]))

In [12]:
def forward_propogation():
    pass
import math

In [70]:
np.random.randn(4,5)*np.sqrt(2./10)


array([[-0.16061471, -0.16025957,  0.0059238 ,  0.13741752,  0.35315246],
       [-0.29075337, -0.03293983,  0.12939195, -0.54396757, -0.23191496],
       [ 0.4121396 ,  0.02060898,  0.00726237,  0.16082287,  0.22030385],
       [-0.13263735,  0.61858634,  0.615989  , -0.62549158,  0.73580714]])

In [66]:
x=np.array([[1,2],[3,6],[4,8]])
y=np.array([[4,5,2],[2,3,55]])
np.dot(x,y)

array([[  8,  11, 112],
       [ 24,  33, 336],
       [ 32,  44, 448]])

In [60]:
class NN:
    def __init__(self,input_size,hidden_size,output_size):
        self.params={
            "W1":np.random.randn(hidden_size,input_size)*np.sqrt(2./input_size),
            "b1":np.zeros((hidden_size,1)),
            "W2":np.random.randn(output_size,hidden_size)*np.sqrt(2./hidden_size),
            "b2":np.zeros((output_size,1))
        }
    def sigmoid(self,z):
        return 1/(1+np.exp(z))
    def ReLU(self,z):
        return np.maximum(0,z)
    def sigmoid_derivative(self,z):
        s=self.sigmoid(z)
        return s*(1-s)
    def ReLU_derivative(self,z):
        return (z>0).astype(float)
    def forward_propogation(self,X):
        W1,b1,W2,b2=self.params["W1"],Self.params["b1"],self.params["W2"],self.params["b2"]
        z1=np.dot(W1,X)+b1
        A1=self.ReLU(z1) 
        z2=np.dot(W2,A1)+b2
        A2=self.sigmoid(z2)
        self.cache={"Z1":z1,"A1":A1,"Z2":z2,"A2":A2}
        return A2
    def compute_cost(self,A2,Y):
        m=Y.shape[1]
        A1=self.cache["A1"]
        A2=self.cache["A2"]
        W2=self.cache["W2"]
        dz2=A2-Y
        dw2=np.dot(dz2,A1.T)

''
    
        

In [ ]:
pow